# Generated by Django 5.2.15 on 2026-06-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shopee_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tiktok_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
