# Generated by Django 5.2.15 on 2026-06-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_shopee_url_product_tiktok_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shopee_regular_url", models.URLField(blank=True, null=True)),
                ("shopee_set_url", models.URLField(blank=True, null=True)),
                ("tiktok_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="shopee_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tiktok_url",
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
