# Generated by Django 5.2.15 on 2026-06-10 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_sitesettings_remove_product_shopee_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
