# Generated by Django 5.2.15 on 2026-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_set_product",
            field=models.BooleanField(default=False),
        ),
    ]
