# Generated by Django 5.2.15 on 2026-06-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_is_set_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="scent",
            field=models.CharField(
                choices=[
                    ("Thara Mist", "Thara Mist"),
                    ("Poised Pear & Freesia", "Poised Pear & Freesia"),
                    ("Aqua No.1", "Aqua No.1"),
                    ("Box Set", "Box Set"),
                    ("Trio Set", "Trio Set"),
                ],
                max_length=100,
            ),
        ),
    ]
