# Generated by Django 5.2.15 on 2026-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_product_scent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
