# Generated by Django 5.2.15 on 2026-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_options_product_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
