# Generated by Django 5.2.15 on 2026-07-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_productannouncement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="productannouncement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product Announcement",
                "verbose_name_plural": "Product Announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="thaimart_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
